FROM nginx:latest

# Set the working directory inside the container
WORKDIR /etc/nginx/

# Copy the requirements file and install dependencies
# COPY . .

# Expose the port your Flask app runs on
EXPOSE 8000

# Define the command to run your Flask application
